### ISSUE TITLE
Recording enabled in settings yet no button in dialer

### ISSUE THREAD

**Issue by privacyguy123** [vvb2060/CallRecording#14]
Seems like my Phone app UI is spoofed to wrong version or something? The record button is nowhere to be found.

**Comment by vvb2060** [comment]
It doesn't look like Google Dialer, maybe the OEM has some customization. Sorry, there's nothing I can do about it

**Comment by privacyguy123** [comment]
Good shout, force disabling OEM dialer stuff fixed it.
