### ISSUE TITLE
There is no option to record all incoming calls and outgoing calls.

### ISSUE THREAD

**Issue by mashunterbd** [vvb2060/CallRecording#15]
![Screenshot_2023-09-30-09-56-33-668_com google android dialer](https://github.com/vvb2060/CallRecording/assets/108648096/7286734a-e77e-4aaa-a4a1-666c6ac5faa2)

Here there is only option to record calls of some selected numbers.  There are many numbers in some contactors, it is very troublesome to select them one by one and start the recording option.  So there was a need to provide all call recording options.  Please enable the option to record all calls.

**Comment by vvb2060** [comment]
https://support.google.com/phoneapp/answer/9803950
Ask Google
