### ISSUE TITLE
Android 13 - Recording Saved, but not showing

### ISSUE THREAD

**Issue by billabongbruno** [vvb2060/CallRecording#17]
Hey there.
So, first of all, thank you for your work.

I have an Android 13 device running CrDroid 9.11 (surya) and use KernelSU and LSPosed.

The option to record does appear in Google Dialer and everything seems to work, but once I end the call or manually stop recording, I get a Recording Saved prompt, but I can't find the recording anywhere.

Would you happen to know where I would find it?

Best regards,
Bruno.

**Comment by vvb2060** [comment]
https://support.google.com/phoneapp/answer/9803950
