### ISSUE TITLE
Samsung device

### ISSUE THREAD

**Issue by wiredroid** [vvb2060/CallRecording#4]
Hi,

This doesn't seem to be working on the downloadable dialler from Play Store for non Google devices. I see the option during call. If I tap record call the record icon disappeas but the words call recording remain. Them when i select stop recording I get a notification saying recording failed. No settings option for recording appears also.

https://play.google.com/store/apps/details?id=com.google.android.dialer

**Comment by vvb2060** [comment]
I can't help you because I downloaded the apk from the url you gave too, this apk works fine in my device.

**Comment by wiredroid** [comment]
It seems to be working. I get the recording button in call but no call recording in settings.

**Comment by vvb2060** [comment]
I can't help you without any information

**Comment by wiredroid** [comment]
https://user-images.githubusercontent.com/86910506/188851228-934da5db-23d0-4892-8523-7ed8c5da9e12.mp4
