### ISSUE TITLE
I was going to make recording for you.

### ISSUE THREAD

**Issue by wiredroid** [vvb2060/CallRecording#5]
https://user-images.githubusercontent.com/86910506/188851491-1370f200-be3f-4fb0-9ccb-bf16b9471df2.mp4

**Comment by vvb2060** [comment]
It doesn't help to solve the problem

**Comment by wiredroid** [comment]
What info do you need to solve it?

**Comment by vvb2060** [comment]
log

**Comment by wiredroid** [comment]
I tried to search error log couldn't see anything. Do you have debug build
of dialler?
