### ISSUE TITLE
Auto record all calls

### ISSUE THREAD

**Issue by michamichamicha** [vvb2060/CallRecording#6]
Would it be possible to extend the functionality to automatically record all calls? For contacts and non-contacts.

**Comment by blackwind** [comment]
Absolutely critical functionality. Weird that Google doesn't offer an option for it, but hopefully @vvb2060 can provide one.

**Comment by vvb2060** [comment]
https://support.google.com/phoneapp/answer/9803950

**Comment by elektrinis** [comment]
It works on latest beta dialer, I am happy that there is no alert "call being recorder".
But I want to enable recording for all calls. Can this module do it in future?

**Comment by Astronxd** [comment]
The dialer app auto records unknown numbers and selected contacts only. Its tedious to manually select all contacts. So please add a feature to record all calls. Thanks

**Comment by elektrinis** [comment]
I have replaced stock dialer with free "ACR phone" dialer with extra helper. It works really well, no warnings, records all calls, quality is good, seemless integration with call log.

**Comment by Astronxd** [comment]
BCR is better imo

**Comment by elektrinis** [comment]
> 

For me recording quality was really bad, also it does not integrate with call log.
