### ISSUE TITLE
Does not work properly on Google Dialer 96.0.499579918 (latest stable version)

### ISSUE THREAD

**Issue by moldimolt** [vvb2060/CallRecording#7]
On my Xperia 1 IV (XQ-CT72) using Google Dialer 96.0.499579918, the latest stable version, call recording settings show when this module is enabled but have no effect, a recording is never generated even with Always record unknown numbers/certain contacts enabled, and the "Record" button does not display on calls. On the public beta version of Google Dialer, it has the same issue with not working, but instead of the "Record" button not showing it shows while the call is connecting, then is replaced by the hold button. 

Please let me know how I can help fix this bug. 

Thank you.

**Comment by vvb2060** [comment]
version 99.0.512778607 work fine
