### ISSUE TITLE
Not working on Pixel7 Pro

### ISSUE THREAD

**Issue by huajijam** [vvb2060/CallRecording#8]
OS Version:TQ1A.230205.002
Google Dialer:99.0.512778607-pixel2022

have record button but Record Fail
log file: [log.log](https://github.com/vvb2060/CallRecording/files/10950470/log.log)

seems to be TTS country problem

![photo_2023-03-12_17-46-57](https://user-images.githubusercontent.com/29218242/224536937-b6b8928f-bbf8-4d5d-8cb8-fd8aa4b0327b.jpg)

**Comment by vvb2060** [comment]
必须启用TTS，不能停用或删除
